# Generated by Django 3.2.10 on 2022-01-02 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
