# Generated by Django 3.2.10 on 2022-01-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='batch',
            field=models.IntegerField(null=True),
        ),
    ]
