# Generated by Django 3.2.10 on 2022-01-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('actualName', models.TextField()),
                ('bio', models.TextField(blank=True)),
                ('batch', models.PositiveIntegerField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('skills', models.TextField()),
                ('contactNum', models.BigIntegerField(blank=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('github', models.URLField(blank=True)),
                ('mlh', models.URLField()),
            ],
        ),
    ]
